### PR TITLE
Remove GGP support

### PR DESCRIPTION
**Pull request by vettoreldaniele**
This also allows us to go back to the mainline `glfw` repository which did not have GGP support.

### CODE REVIEW

**Comment by vettoreldaniele** [comment]
> Thank you!
> 
> This will require changes to the internal importer, right?

Why? I don't think so unless I'm missing something?

**Comment by dnovillo** [comment]
> > Thank you!
> > This will require changes to the internal importer, right?
> 
> Why? I don't think so unless I'm missing something?

The location of glfw.  Or is the internal mirror already using upstream?

**Comment by vettoreldaniele** [comment]
> 



> > > Thank you!
> > > This will require changes to the internal importer, right?
> > 
> > 
> > Why? I don't think so unless I'm missing something?
> 
> The location of glfw. Or is the internal mirror already using upstream?

Already using upstream!

**Comment by dnovillo** [comment]
> > 
> 
> > > > Thank you!
> > > > This will require changes to the internal importer, right?
> > > 
> > > 
> > > Why? I don't think so unless I'm missing something?
> > 
> > 
> > The location of glfw. Or is the internal mirror already using upstream?
> 
> Already using upstream!

Excellent!  Thanks :)

**Pull request merged**
