### PR TITLE
Change C++ standard to C++17.

### PR DESCRIPTION
**Pull request by hysw**
C++20 is not well support with all our compilation environments.

### CODE REVIEW

**Comment by hysw** [comment]
So some additional context on the C++ standard version:

- Our presubmit runs on clang 10 (Linux) and 12 (Android NDK23), so C++20 is not particularly well supported. (e.g. NDK issue [1886](https://github.com/android/ndk/issues/1886) )
- We got very little benefit from C++20, there's around 30 lines of code uses C++20 features, and non of their functionality actually requires C++20 features.
- We've already spend hours dealing with C++20 related issues ( #210 ; #262 ; #265 ; #266 )
- In addition, other Google open source projects uses up to C++17.

**Review by Keenuts — APPROVED** [review]
Fine with me, since `c++20` is causing more issues than it brings benefits for now.
(I largely prefer this to local patches here and there to be c++17 compliant).

**Comment by chaoticbob** [comment]
Can you add a line to main README.md that says something along the lines of C++17 compliant compiler? Maybe a bullet point under the Requirements?

**Comment by hysw** [comment]
> Can you add a line to main README.md that says something along the lines of C++17 compliant compiler? Maybe a bullet point under the Requirements?

Added to both `README.md` and `CONTRIBUTING.md`
* `README.md` Linux requirement: clang 10 is our presubmit, and gcc 9 is fully C++17 compliant
* `README.md` MSVC 2019 can compile up to C++20, so it's a higher requirement than a C++17 compliant compiler
* `CONTRIBUTING.md` since that's where submission requirement is listed

**Review by chaoticbob — APPROVED** [review]
LGTM

**Pull request merged**
