### PR TITLE
Explicitly set the gradle build action version

### PR DESCRIPTION
**Pull request by apazylbe**
There seems to be a vulnerability fixed in 2.4.2.

### CODE REVIEW

**Comment by Keenuts** [comment]
Isn't the security report saying `v2` is fine? (as it's automatically updated to the latest v2.x.x ?)

**Comment by Keenuts** [comment]
(I don't understand why the error is still showing TBH, the report says "no action required", and we have no cache)

**Comment by Keenuts** [comment]
Let's try merge, see if it solves, and then revert?
I don't want to fix the version as we won't be able to benefit from those patches in the future if we hardcode `v2.4.2`.

**Comment by apazylbe** [comment]
Makes sense, it looks like this was published recently, so maybe there will be a better automated check for it later? agree, that it's better to have v2 so we get the latest

**Review by Keenuts — APPROVED** [review]

**Comment by Keenuts** [comment]
Alert is closed.

**Pull request merged**
