### PR TITLE
Add multisample to foveation app

### PR DESCRIPTION
**Pull request by jorgeag-google**
Makes the foveation app able to use multisample foveation

This change was missing from the previous PR #493

### CODE REVIEW

**Review by apazylbe — COMMENTED** [review]
Did you run with validation layers? I assume it creates correct multisampled images for render target?

**Comment by jorgeag-google** [comment]
I run it on device with both methods and saw the foveation pattern working
I run a debug build (on Android) and then look in the logcat and saw no errors.
So I assume it has the validation layers, but not sure

**Comment by apazylbe** [comment]
We don't enable validation layers by default on debug Android builds, https://github.com/google/bigwheels/blob/5ea74e5741cd53be7c88632eec9aad943740f0ac/include/ppx/application.h#L146 just cause they take additional steps to set up. 
Overall LGTM, I would just double check with validation layers just in case.

**Review by apazylbe — APPROVED** [review]

**Review by wangra-google — APPROVED** [review]

**Comment by jorgeag-google** [comment]
So, there is a validation error: 
```
VUID-VkSwapchainCreateInfoKHR-compositeAlpha-01280(ERROR / SPEC): msgNum: -1341842926 - Validation Error:
[ VUID-VkSwapchainCreateInfoKHR-compositeAlpha-01280 ] | MessageID = 0xb0051a12 | vkCreateSwapchainKHR(): pCreateInfo->compositeAlpha is not supported, support values are: VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR%s                                                                                                    . The Vulkan spec states: compositeAlpha must be one of the bits present in the supportedCompositeAlpha member of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-compositeAlpha-01280)
```
But there is common to all application on the device rather than just the foveation app

**Pull request merged**
